### ISSUE TITLE
Encoding special tokens bug

### ISSUE THREAD

**Issue by ronaldmannak** [KelvinJin/SwiftikToken#1]
There seems to be an issue encoding special tokens. For example, encoding special token `<|endoftext|>` using GPT2 should return [50256] but returns [27, 50256]. 27 is the token for `<`. 
The code below uses GPT2. However, all models have the same issue. They all return the token for '<' followed by the correct token for `<|endoftext|>` in the specific model.

```swift
  let text = "<|endoftext|>"
  let tokenizer = Tiktoken(encoding: .p50k)
  let tokens = try await tokenizer.encode(text: text, allowedSpecial: Set(["all"]))
  // Expected: [50256]
  // Actually returned: [27, 50256]
  // 27 equals "<"
```

**Comment by KelvinJin** [comment]
Hi there, thanks for reporting the issue. This is such a good pickup! Sorry for the late response. It's due to a misuse on the range operator (..< instead of ...). I have fixed this in the latest commit 753b483eff4b6aec61e739b47a82344184663063. The new version 1.0.4 contains this fix.
